### ISSUE TITLE
there is no directory called SegmentationClassAug,how to solve it

### ISSUE THREAD

**Issue by pubEgg** [TheLegendAli/DeepLab-Context#10]
when i run deeplab, error :Could not open or find file /home/odvs/VOC2012_new/SegmentationClassAug/2008_002444.png

hoe to solve it.

**Comment by TheLegendAli** [comment]
That looks like a path issue, os that the correct path to image 2008_002444.png?

**Comment by pubEgg** [comment]
@TheLegendAli 
there is no the directory /SegmentationClassAug, it is the expanded one, i don't know where to find it.
now i use the standard voc2012, remake train_aug.txt.
but with the problem out of memory ,  I use k2200, is the memory too small?

**Comment by TheLegendAli** [comment]
That's the path you use for the labeled pixels. We used hariharan's annotations. If you have the pixel by pixel annotation for images, change the path to that image set.

**Comment by TheLegendAli** [comment]
you can download them from my dropbox:

https://www.dropbox.com/s/oeu149j8qtbs1x0/SegmentationClassAug.zip?dl=0

**Comment by pubEgg** [comment]
@TheLegendAli Thank you! it works

**Comment by pkuCactus** [comment]
@TheLegendAli could you tell me how did you get the SegmentationClassAug, i found there is some inconsitency label with pascal voc's ground truth? thanks a lot.

**Comment by TheLegendAli** [comment]
was given to me by George Papandreou. What's the inconsistency, perhaps I uploaded the wrong file

**Comment by icoz69** [comment]
@TheLegendAli hi,why segmentationClassAug consists of boundary maps rather than segmentation maps which have class information?
