### ISSUE TITLE
Reading .mat files

### ISSUE THREAD

**Issue by codecolony** [TheLegendAli/DeepLab-Context#24]
Hi,

I get .mat files as output but I don't have matlab. I heard we can use matio or scipy to read them but the shape of the array is like (579,579,21,1). I can't figure how to see them as images. Any help, pointers or suggestions are appreciated.

Thanks for sharing the wonderful project.

**Comment by ghost** [comment]
you can execute this in octave 4.2.x:
```
% First, double click on the  result *.mat file  e.g. 2008_000143_blob_0.mat

colormap=load('<your_root_deeplab_directory>/matlab/my_script/pascal_seg_colormap.mat');


raw_result = permute(data, [2 1 3]);
[~, result] = max(raw_result, [], 3);
result = uint8(result) - 1;

imshow(result, colormap.colormap);
```

**Comment by codecolony** [comment]
@mojovski  - Thank you very much! It helped me a lot.
