### ISSUE TITLE
What do pointers to CAFFE_BIN and CAFFE_DIR mean?

### ISSUE THREAD

**Issue by anuragranj** [TheLegendAli/DeepLab-Context#3]
In `DeepLab-Context/python/my_script/tools.py` lines 39-40

```
CAFFE_DIR='./'
CAFFE_BIN='.build_release/tools/caffe.bin'
```

Do they just point to where caffe is installed in the system, or is it to create local directories considering it is a part of mkdir function?

**Comment by VittalP** [comment]
CAFFE_DIR points to the Caffe root.
CAFFE_BIN points to compiled binary file.

They just point to where caffe is installed, which is then used to create a dictionary.

**Comment by archenroot** [comment]
I have on my system following files installed:
`ares caffe # equery f caffe
 * Searching for caffe ...
 * Contents of dev-libs/caffe-1.0:
/usr
/usr/bin
/usr/bin/caffe
/usr/bin/classification
/usr/bin/classify.py -> ../lib/python-exec/python-exec2
/usr/bin/compute_image_mean
/usr/bin/convert_cifar_data
/usr/bin/convert_imageset
/usr/bin/convert_mnist_data
/usr/bin/convert_mnist_siamese_data
/usr/bin/detect.py -> ../lib/python-exec/python-exec2
/usr/bin/device_query
/usr/bin/draw_net.py -> ../lib/python-exec/python-exec2
/usr/bin/extract_features
/usr/bin/finetune_net
/usr/bin/net_speed_benchmark
/usr/bin/test_net
/usr/bin/train_net
/usr/bin/upgrade_net_proto_binary
/usr/bin/upgrade_net_proto_text
/usr/bin/upgrade_solver_proto_text
/usr/include
/usr/include/caffe
/usr/include/caffe/blob.hpp
/usr/include/caffe/caffe.hpp
/usr/include/caffe/common.hpp
/usr/include/caffe/data_reader.hpp
/usr/include/caffe/data_transformer.hpp
/usr/include/caffe/filler.hpp
/usr/include/caffe/internal_thread.hpp
/usr/include/caffe/layer.hpp
/usr/include/caffe/layer_factory.hpp
/usr/include/caffe/layers
/usr/include/caffe/layers/absval_layer.hpp
/usr/include/caffe/layers/accuracy_layer.hpp
/usr/include/caffe/layers/argmax_layer.hpp
/usr/include/caffe/layers/base_conv_layer.hpp
/usr/include/caffe/layers/base_data_layer.hpp
/usr/include/caffe/layers/batch_norm_layer.hpp
/usr/include/caffe/layers/batch_reindex_layer.hpp
/usr/include/caffe/layers/bias_layer.hpp
/usr/include/caffe/layers/bnll_layer.hpp
/usr/include/caffe/layers/concat_layer.hpp
/usr/include/caffe/layers/contrastive_loss_layer.hpp
/usr/include/caffe/layers/conv_layer.hpp
/usr/include/caffe/layers/crop_layer.hpp
/usr/include/caffe/layers/cudnn_conv_layer.hpp
/usr/include/caffe/layers/cudnn_lcn_layer.hpp
/usr/include/caffe/layers/cudnn_lrn_layer.hpp
/usr/include/caffe/layers/cudnn_pooling_layer.hpp
/usr/include/caffe/layers/cudnn_relu_layer.hpp
/usr/include/caffe/layers/cudnn_sigmoid_layer.hpp
/usr/include/caffe/layers/cudnn_softmax_layer.hpp
/usr/include/caffe/layers/cudnn_tanh_layer.hpp
/usr/include/caffe/layers/data_layer.hpp
/usr/include/caffe/layers/deconv_layer.hpp
/usr/include/caffe/layers/dropout_layer.hpp
/usr/include/caffe/layers/dummy_data_layer.hpp
/usr/include/caffe/layers/eltwise_layer.hpp
/usr/include/caffe/layers/elu_layer.hpp
/usr/include/caffe/layers/embed_layer.hpp
/usr/include/caffe/layers/euclidean_loss_layer.hpp
/usr/include/caffe/layers/exp_layer.hpp
/usr/include/caffe/layers/filter_layer.hpp
/usr/include/caffe/layers/flatten_layer.hpp
/usr/include/caffe/layers/hdf5_data_layer.hpp
/usr/include/caffe/layers/hdf5_output_layer.hpp
/usr/include/caffe/layers/hinge_loss_layer.hpp
/usr/include/caffe/layers/im2col_layer.hpp
/usr/include/caffe/layers/image_data_layer.hpp
/usr/include/caffe/layers/infogain_loss_layer.hpp
/usr/include/caffe/layers/inner_product_layer.hpp
/usr/include/caffe/layers/input_layer.hpp
/usr/include/caffe/layers/log_layer.hpp
/usr/include/caffe/layers/loss_layer.hpp
/usr/include/caffe/layers/lrn_layer.hpp
/usr/include/caffe/layers/lstm_layer.hpp
/usr/include/caffe/layers/memory_data_layer.hpp
/usr/include/caffe/layers/multinomial_logistic_loss_layer.hpp
/usr/include/caffe/layers/mvn_layer.hpp
/usr/include/caffe/layers/neuron_layer.hpp
/usr/include/caffe/layers/parameter_layer.hpp
/usr/include/caffe/layers/pooling_layer.hpp
/usr/include/caffe/layers/power_layer.hpp
/usr/include/caffe/layers/prelu_layer.hpp
/usr/include/caffe/layers/python_layer.hpp
/usr/include/caffe/layers/recurrent_layer.hpp
/usr/include/caffe/layers/reduction_layer.hpp
/usr/include/caffe/layers/relu_layer.hpp
/usr/include/caffe/layers/reshape_layer.hpp
/usr/include/caffe/layers/rnn_layer.hpp
/usr/include/caffe/layers/scale_layer.hpp
/usr/include/caffe/layers/sigmoid_cross_entropy_loss_layer.hpp
/usr/include/caffe/layers/sigmoid_layer.hpp
/usr/include/caffe/layers/silence_layer.hpp
/usr/include/caffe/layers/slice_layer.hpp
/usr/include/caffe/layers/softmax_layer.hpp
/usr/include/caffe/layers/softmax_loss_layer.hpp
/usr/include/caffe/layers/split_layer.hpp
/usr/include/caffe/layers/spp_layer.hpp
/usr/include/caffe/layers/tanh_layer.hpp
/usr/include/caffe/layers/threshold_layer.hpp
/usr/include/caffe/layers/tile_layer.hpp
/usr/include/caffe/layers/window_data_layer.hpp
/usr/include/caffe/net.hpp
/usr/include/caffe/parallel.hpp
/usr/include/caffe/proto
/usr/include/caffe/proto/caffe.pb.h
/usr/include/caffe/sgd_solvers.hpp
/usr/include/caffe/solver.hpp
/usr/include/caffe/solver_factory.hpp
/usr/include/caffe/syncedmem.hpp
/usr/include/caffe/test
/usr/include/caffe/test/test_caffe_main.hpp
/usr/include/caffe/test/test_gradient_check_util.hpp
/usr/include/caffe/util
/usr/include/caffe/util/benchmark.hpp
/usr/include/caffe/util/blocking_queue.hpp
/usr/include/caffe/util/cudnn.hpp
/usr/include/caffe/util/db.hpp
/usr/include/caffe/util/db_leveldb.hpp
/usr/include/caffe/util/db_lmdb.hpp
/usr/include/caffe/util/device_alternate.hpp
/usr/include/caffe/util/format.hpp
/usr/include/caffe/util/gpu_util.cuh
/usr/include/caffe/util/hdf5.hpp
/usr/include/caffe/util/im2col.hpp
/usr/include/caffe/util/insert_splits.hpp
/usr/include/caffe/util/io.hpp
/usr/include/caffe/util/math_functions.hpp
/usr/include/caffe/util/mkl_alternate.hpp
/usr/include/caffe/util/rng.hpp
/usr/include/caffe/util/signal_handler.h
/usr/include/caffe/util/upgrade_proto.hpp
/usr/lib
/usr/lib/python-exec
/usr/lib/python-exec/python3.4
/usr/lib/python-exec/python3.4/classify.py
/usr/lib/python-exec/python3.4/detect.py
/usr/lib/python-exec/python3.4/draw_net.py
/usr/lib64
/usr/lib64/libcaffe.a
/usr/lib64/libcaffe.so -> libcaffe.so.1.0.0-rc3
/usr/lib64/libcaffe.so.1.0.0-rc3
/usr/lib64/python3.4
/usr/lib64/python3.4/site-packages
/usr/lib64/python3.4/site-packages/caffe
/usr/lib64/python3.4/site-packages/caffe/__init__.py
/usr/lib64/python3.4/site-packages/caffe/__pycache__
/usr/lib64/python3.4/site-packages/caffe/__pycache__/__init__.cpython-34.pyc
/usr/lib64/python3.4/site-packages/caffe/__pycache__/__init__.cpython-34.pyo
/usr/lib64/python3.4/site-packages/caffe/__pycache__/classifier.cpython-34.pyc
/usr/lib64/python3.4/site-packages/caffe/__pycache__/classifier.cpython-34.pyo
/usr/lib64/python3.4/site-packages/caffe/__pycache__/coord_map.cpython-34.pyc
/usr/lib64/python3.4/site-packages/caffe/__pycache__/coord_map.cpython-34.pyo
/usr/lib64/python3.4/site-packages/caffe/__pycache__/detector.cpython-34.pyc
/usr/lib64/python3.4/site-packages/caffe/__pycache__/detector.cpython-34.pyo
/usr/lib64/python3.4/site-packages/caffe/__pycache__/draw.cpython-34.pyc
/usr/lib64/python3.4/site-packages/caffe/__pycache__/draw.cpython-34.pyo
/usr/lib64/python3.4/site-packages/caffe/__pycache__/io.cpython-34.pyc
/usr/lib64/python3.4/site-packages/caffe/__pycache__/io.cpython-34.pyo
/usr/lib64/python3.4/site-packages/caffe/__pycache__/net_spec.cpython-34.pyc
/usr/lib64/python3.4/site-packages/caffe/__pycache__/net_spec.cpython-34.pyo
/usr/lib64/python3.4/site-packages/caffe/__pycache__/pycaffe.cpython-34.pyc
/usr/lib64/python3.4/site-packages/caffe/__pycache__/pycaffe.cpython-34.pyo
/usr/lib64/python3.4/site-packages/caffe/_caffe.so
/usr/lib64/python3.4/site-packages/caffe/classifier.py
/usr/lib64/python3.4/site-packages/caffe/coord_map.py
/usr/lib64/python3.4/site-packages/caffe/detector.py
/usr/lib64/python3.4/site-packages/caffe/draw.py
/usr/lib64/python3.4/site-packages/caffe/imagenet
/usr/lib64/python3.4/site-packages/caffe/imagenet/ilsvrc_2012_mean.npy
/usr/lib64/python3.4/site-packages/caffe/io.py
/usr/lib64/python3.4/site-packages/caffe/net_spec.py
/usr/lib64/python3.4/site-packages/caffe/proto
/usr/lib64/python3.4/site-packages/caffe/proto/__init__.py
/usr/lib64/python3.4/site-packages/caffe/proto/__pycache__
/usr/lib64/python3.4/site-packages/caffe/proto/__pycache__/__init__.cpython-34.pyc
/usr/lib64/python3.4/site-packages/caffe/proto/__pycache__/__init__.cpython-34.pyo
/usr/lib64/python3.4/site-packages/caffe/proto/__pycache__/caffe_pb2.cpython-34.pyc
/usr/lib64/python3.4/site-packages/caffe/proto/__pycache__/caffe_pb2.cpython-34.pyo
/usr/lib64/python3.4/site-packages/caffe/proto/caffe_pb2.py
/usr/lib64/python3.4/site-packages/caffe/pycaffe.py
/usr/lib64/python3.4/site-packages/caffe/test
/usr/lib64/python3.4/site-packages/caffe/test/__pycache__
/usr/lib64/python3.4/site-packages/caffe/test/__pycache__/test_coord_map.cpython-34.pyc
/usr/lib64/python3.4/site-packages/caffe/test/__pycache__/test_coord_map.cpython-34.pyo
/usr/lib64/python3.4/site-packages/caffe/test/__pycache__/test_io.cpython-34.pyc
/usr/lib64/python3.4/site-packages/caffe/test/__pycache__/test_io.cpython-34.pyo
/usr/lib64/python3.4/site-packages/caffe/test/__pycache__/test_layer_type_list.cpython-34.pyc
/usr/lib64/python3.4/site-packages/caffe/test/__pycache__/test_layer_type_list.cpython-34.pyo
/usr/lib64/python3.4/site-packages/caffe/test/__pycache__/test_net.cpython-34.pyc
/usr/lib64/python3.4/site-packages/caffe/test/__pycache__/test_net.cpython-34.pyo
/usr/lib64/python3.4/site-packages/caffe/test/__pycache__/test_net_spec.cpython-34.pyc
/usr/lib64/python3.4/site-packages/caffe/test/__pycache__/test_net_spec.cpython-34.pyo
/usr/lib64/python3.4/site-packages/caffe/test/__pycache__/test_python_layer.cpython-34.pyc
/usr/lib64/python3.4/site-packages/caffe/test/__pycache__/test_python_layer.cpython-34.pyo
/usr/lib64/python3.4/site-packages/caffe/test/__pycache__/test_python_layer_with_param_str.cpython-34.pyc
/usr/lib64/python3.4/site-packages/caffe/test/__pycache__/test_python_layer_with_param_str.cpython-34.pyo
/usr/lib64/python3.4/site-packages/caffe/test/__pycache__/test_solver.cpython-34.pyc
/usr/lib64/python3.4/site-packages/caffe/test/__pycache__/test_solver.cpython-34.pyo
/usr/lib64/python3.4/site-packages/caffe/test/test_coord_map.py
/usr/lib64/python3.4/site-packages/caffe/test/test_io.py
/usr/lib64/python3.4/site-packages/caffe/test/test_layer_type_list.py
/usr/lib64/python3.4/site-packages/caffe/test/test_net.py
/usr/lib64/python3.4/site-packages/caffe/test/test_net_spec.py
/usr/lib64/python3.4/site-packages/caffe/test/test_python_layer.py
/usr/lib64/python3.4/site-packages/caffe/test/test_python_layer_with_param_str.py
/usr/lib64/python3.4/site-packages/caffe/test/test_solver.py
`

**So what is CAFFE_DIR?** 

CAFFE_BIN = /usr/bin/caffe in my case
